return {
	"VonHeikemen/lsp-zero.nvim",
	dependancies={
		{"neovim/nvim-lspconfig"},
		{"williamboman/mason.nvim"},
		{"williamboman/mason-lspconfig.nvim"},
		{"hrsh7th/nvim-cmp"},
		{"hrsh7th/cmp-nvim-lsp"},
		{"hrsh7th/cmp-buffer"},
		{"hrsh7th/cmp-path"},
		{"saadparwaiz1/cmp_luasnip"},
		{"L3MON4D3/LuaSnip"},
		{"rafamadriz/friendly-snippets"}
	},
	{"neovim/nvim-lspconfig"},
	{"williamboman/mason.nvim"},
	{"williamboman/mason-lspconfig.nvim"},
	{"hrsh7th/nvim-cmp"},
	{"hrsh7th/cmp-nvim-lsp"},
	{"hrsh7th/cmp-buffer"},
	{"hrsh7th/cmp-path"},
	{"saadparwaiz1/cmp_luasnip"},
	{"L3MON4D3/LuaSnip"},
	{"rafamadriz/friendly-snippets"}
}
